-- MySQL Script generated by MySQL Workbench
-- Mon Feb  8 17:15:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fairychar-uaa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fairychar-uaa` ;

-- -----------------------------------------------------
-- Schema fairychar-uaa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fairychar-uaa` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `fairychar-uaa` ;

-- -----------------------------------------------------
-- Table `fairychar-uaa`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fairychar-uaa`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fairychar-uaa`.`customer` (
  `id` INT(8) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `name` VARCHAR(45) NOT NULL COMMENT '用户名',
  `password` VARCHAR(255) NOT NULL COMMENT '密码',
  `tel` VARCHAR(20) NOT NULL COMMENT '手机号',
  `email` VARCHAR(245) NULL COMMENT '邮箱',
  `birthday` DATE NOT NULL COMMENT '生日',
  `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
  `version` BIGINT(19) NOT NULL DEFAULT 0 COMMENT '乐观锁',
  `flag` INT(1) NOT NULL DEFAULT 0 COMMENT '是否逻辑逻辑删除',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `tel_UNIQUE` ON `fairychar-uaa`.`customer` (`tel` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `fairychar-uaa`.`customer` (`email` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fairychar-uaa`.`authority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fairychar-uaa`.`authority` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fairychar-uaa`.`authority` (
  `id` INT(8) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `authoritycol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fairychar-uaa`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fairychar-uaa`.`role` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fairychar-uaa`.`role` (
  `id` INT(8) NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT '角色名声',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fairychar-uaa`.`role_authority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fairychar-uaa`.`role_authority` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fairychar-uaa`.`role_authority` (
  `id` INT(8) NOT NULL,
  `authority_id` INT(8) NOT NULL COMMENT '权限表id',
  `role_id` INT(8) NOT NULL COMMENT '角色表id',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_authority_has_role_authority`
    FOREIGN KEY (`authority_id`)
    REFERENCES `fairychar-uaa`.`authority` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_authority_has_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `fairychar-uaa`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_authority_has_role_role1_idx` ON `fairychar-uaa`.`role_authority` (`role_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_authority_has_role_authority_idx` ON `fairychar-uaa`.`role_authority` (`authority_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fairychar-uaa`.`customer_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fairychar-uaa`.`customer_role` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fairychar-uaa`.`customer_role` (
  `id` INT(8) NOT NULL,
  `customer_id` INT(8) NOT NULL COMMENT '用户表id',
  `role_id` INT(8) NOT NULL COMMENT '角色表id',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_customer_has_role_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `fairychar-uaa`.`customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_customer_has_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `fairychar-uaa`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_customer_has_role_role1_idx` ON `fairychar-uaa`.`customer_role` (`role_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_customer_has_role_customer1_idx` ON `fairychar-uaa`.`customer_role` (`customer_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fairychar-uaa`.`organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fairychar-uaa`.`organization` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fairychar-uaa`.`organization` (
  `id` INT(8) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '机构名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fairychar-uaa`.`organization_customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fairychar-uaa`.`organization_customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fairychar-uaa`.`organization_customer` (
  `id` INT(8) NOT NULL,
  `customer_id` INT(8) NOT NULL,
  `organization_id` INT(8) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_customer_has_organization_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `fairychar-uaa`.`customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_customer_has_organization_organization1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `fairychar-uaa`.`organization` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_customer_has_organization_organization1_idx` ON `fairychar-uaa`.`organization_customer` (`organization_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_customer_has_organization_customer1_idx` ON `fairychar-uaa`.`organization_customer` (`customer_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
