fairychar:
  bag:
    aop:
      lock:
        enable: false
        time-unit: seconds
        global-timeout: 1
        default-lock: redis
      log:
        enable: false
        global-before: swagger
        global-level: info
      binding:
        enable: false
    convert:
      mvc:
        enable: false
    server-client:
      server:
        boss-size: 1
        worker-size: 1
        port: 10000
