fairychar:
  bag:
    aop:
      lock:
        enable: true
        time-unit: seconds
        global-timeout: 1
        default-lock: redis
      log:
        enable: true
        global-before: swagger
        global-level: info
      binding:
        enable: true
    convert:
      mvc:
        enable: true
